Repository eipm/bridge2ai-docs, pull requests merged in 2024-11, with the labels that each got.

#19 B2AI-538
  README.md
  src/dashboard.py
  src/tabs/overview.py
Labels: enhancement

#20 B2AI-544
  css/dashboard.css
  images/ai-readiness-figure-1.png
  requirements.txt
  src/bids-like_structure_preview.html
  src/dashboard.py
  src/tabs/ai_readiness.py
  src/tabs/collection_methods.py
  src/tabs/data_pre_processing.py
  src/tabs/dataset_structure_preview.py
  src/tabs/overview.py
  src/tabs/utils.py
  tables/Acoustic_Tasks_Protocol.csv
  tables/Disease_cohort_inclusion_exclusion_criteria.csv
  tables/Validated_Questionnaires.csv
Labels: enhancement

#22 B2AI-540
  src/tabs/data_governance.py
  src/tabs/healthsheet.py
Labels: enhancement

#23 B2AI-541
  src/tabs/collection_methods.py
  src/tabs/study_metadata.py
  src/tabs/utils.py
Labels: enhancement

#24 v1.2.0
  README.md
  css/dashboard.css
  images/ai-readiness-figure-1.png
  requirements.txt
  src/bids-like_structure_preview.html
  src/dashboard.py
  src/tabs/about.py
  src/tabs/ai_readiness.py
  src/tabs/collection_methods.py
  src/tabs/data_governance.py
  src/tabs/data_pre_processing.py
  src/tabs/dataset_metadata.py
  src/tabs/dataset_quality_dashboard.py
  src/tabs/dataset_structure_preview.py
  src/tabs/dataset_uses.py
  src/tabs/healthsheet.py
  src/tabs/overview.py
  src/tabs/study_metadata.py
  src/tabs/utils.py
  tables/Acoustic_Tasks_Protocol.csv
  tables/Disease_cohort_inclusion_exclusion_criteria.csv
  tables/Validated_Questionnaires.csv
Labels: enhancement

#25 typo fix
  README.md
  src/dashboard.py
  src/tabs/healthsheet.py
Labels: bug

#26 v1.2.1
  README.md
  src/dashboard.py
  src/tabs/healthsheet.py
Labels: bug

#28 B2AI-545
  README.md
  css/dashboard.css
  src/dashboard.py
  src/tabs/ai_readiness.py
  src/tabs/healthsheet.py
  src/tabs/overview.py
  src/tabs/study_dashboard.py
  src/tabs/study_metadata.py
  src/tabs/utils.py
Labels: bug, enhancement

#29 v1.3.0
  README.md
  css/dashboard.css
  src/dashboard.py
  src/tabs/ai_readiness.py
  src/tabs/healthsheet.py
  src/tabs/overview.py
  src/tabs/study_dashboard.py
  src/tabs/study_metadata.py
  src/tabs/utils.py
Labels: enhancement
