Repository eipm/bridge2ai-docs, pull requests merged in 2025-01, with the labels that each got.

#33 B2AI-552
  src/dashboard.py
  src/tabs/overview.py
Labels: bug

#35 Updated README.md version to v1.3.2
  README.md
Labels: documentation

#36 B2AI-553
  README.md
  src/dashboard.py
  src/tabs/overview.py
Labels: enhancement
